[tool.poetry]
name = "csp-classifier"
version = "0.1.0"
description = "Tool for recording, visualizing and analyzing EEG data"
authors = ["Stanisław Zakrzewski <stanislaw.zakrzewski13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.6"
mne = "^1.10.1"
seaborn = "^0.13.2"
scikit-learn = "^1.7.2"
pyedflib = "^0.1.42"
tensorly = "^0.9.0"
progress = "^1.6.1"
scipy = "^1.16.2"
pyaudio = "^0.2.14"
python-vlc = "^3.0.21203"
wheel = "^0.45.1"
setuptools = "^80.9.0"
playsound3 = "^3.2.6"
cffi = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
